name: "Lint PR"
on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  title:
    name: Title
    if: github.event.action == 'opened' || github.event.changes.title.from
    runs-on: ubuntu-latest
    steps:
      - uses: geo-engine/conventional-pr-title@main
        with:
          types: |-
            build
            ci
            docs
            feat
            fix
            perf
            refactor
            test
          scopes: |-
            ascope
            anotherscope
